#### Without NumPy:

In [4]:
my_lst = [num for num in range(1,11)]
print(my_lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


#### Convert to array via Numpy:

In [6]:
import numpy as np

In [8]:
arr = np.array(my_lst)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


#### With NumPy:

In [10]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


#### Creating an array of 5's

In [11]:
arr_fives = np.zeros(10) + 5
print(arr_fives)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Creating an identity matrix

In [12]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Reshaping array

In [13]:
random_arr = np.random.randint(1,51,10).reshape(5,2)
print(random_arr)

[[47 50]
 [43 13]
 [ 2 32]
 [ 8 38]
 [ 1 34]]


#### Finding max value within an array + its index

In [14]:
random_arr.max()

50

In [15]:
random_arr.argmax()

1

In [34]:
random_arr[0,1]

50

#### Creating 5x4 matrix

In [17]:
random_mtrx = np.random.randint(1,101,20).reshape(5,4)
print(random_mtrx)

[[62 19 36 10]
 [93 43 68 42]
 [91 68 45 19]
 [55 55 77 81]
 [82 51 72 63]]


#### Slicing 3th row till (including) last row, second number till (including) end of row

In [18]:
random_mtrx[2:, 1:]

array([[68, 45, 19],
       [55, 77, 81],
       [51, 72, 63]])

#### Getting all the values within random_mtrx that are higher than 50 back

In [19]:
random_mtrx[random_mtrx > 50]

array([62, 93, 68, 91, 68, 55, 55, 77, 81, 82, 51, 72, 63])

#### Operations with arrays

In [20]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [21]:
print(arr*arr)

[  1   4   9  16  25  36  49  64  81 100]


In [22]:
print(arr**2)

[  1   4   9  16  25  36  49  64  81 100]


In [23]:
new_arr = [1,4,9,16,25,36]
print(new_arr)

[1, 4, 9, 16, 25, 36]


In [24]:
np.sqrt(new_arr)

array([1., 2., 3., 4., 5., 6.])

#### Generate an array of 25 random numbers sampled from a standard normal distribution

In [25]:
sample = np.random.randn(25)
print(sample)

[-0.2449262  -0.0707211  -0.04007078  1.51054476 -0.16401775  0.03024214
  1.29826584 -0.86555354 -0.40627787 -1.89845078  0.13933981 -0.90744746
 -1.26274054 -1.37930055  0.31293176 -0.43110908  1.46710544 -0.97791886
  0.2571951  -1.03838036 -1.30696296 -0.74971551 -0.61758685  1.55783334
 -1.64497811]


#### Create an array of 20 linearly spaced points between 0 and 1

In [26]:
lin_array = np.linspace(0,1,20).reshape(20,1)
print(lin_array)

[[0.        ]
 [0.05263158]
 [0.10526316]
 [0.15789474]
 [0.21052632]
 [0.26315789]
 [0.31578947]
 [0.36842105]
 [0.42105263]
 [0.47368421]
 [0.52631579]
 [0.57894737]
 [0.63157895]
 [0.68421053]
 [0.73684211]
 [0.78947368]
 [0.84210526]
 [0.89473684]
 [0.94736842]
 [1.        ]]


#### Sum elements of 1) whole matrix, 2) each row and 3) each column

In [27]:
new_mat = np.arange(1,51).reshape(10,5)
print(new_mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [28]:
print(new_mat.sum())

1275


In [29]:
print(new_mat.sum(axis=1))

[ 15  40  65  90 115 140 165 190 215 240]


In [30]:
print(new_mat.sum(axis=0))

[235 245 255 265 275]


#### Get the standard deviation of the values in new_mat

In [33]:
print(new_mat.std())

14.430869689661812
